version: '3.8'
services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3006:3006"

volumes:
  db_data: