version: '3.8'
services:
  cli:
    image: cli:1.1
    restart: always
    volumes:
      - ../../resources:/home/resources

    entrypoint: [ "/bin/bash", "-c" ]
    command: [ "tail -f /dev/null" ]
